version: '3.8'

services:
  app:
    build: .  # Build the Docker image from the current directory
    ports:
      - "8079:8079"  # Expose port 8079 of the container to the host
    volumes:
      - .:/app  # Mount the current directory into /app in the container for live updates
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/multimicroserviceSaveUser  # PostgreSQL connection URL for Spring Boot
      - SPRING_DATASOURCE_USERNAME=postgres  # Database username
      - SPRING_DATASOURCE_PASSWORD=Shakti  # Database password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update  # Hibernate DDL auto for schema updates
    depends_on:
      - db  # Ensure the database is up before starting the app

  db:
    image: postgres:15  # Use the official PostgreSQL 15 image
    container_name: postgres-db  # Name the PostgreSQL container
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    environment:
      POSTGRES_DB: multimicroserviceSaveUser  # Database name
      POSTGRES_USER: postgres  # PostgreSQL username
      POSTGRES_PASSWORD: Shakti  # PostgreSQL password
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist PostgreSQL data

volumes:
  db_data: {}  # Define a volume for persisting database data
