server:
  port: 8042  # Port for the Eureka Server

eureka:
  instance:
    hostname: localhost # Hostname for the server

  client:
    register-with-eureka: false # Eureka Server itself should not register with Eureka
    fetch-registry: false       # Eureka Server does not fetch registry from itself
#